name: Example Workflow

on:
  push:
    branches:
      - main  # Replace with your default branch name
  schedule:
    - cron: "* * * * *"  # Runs every 5 minutes for testing

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Hello, World!"
