name: Update Database

on:
  schedule:
    - cron: '* * * * *'

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Python 3.13.0
      - name: Set up Python 3.13.0
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.0

      # Step 2: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up Git user
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 5: Run each data processing script
      - name: Run script 1
        run: python app.py

      # Step 6: Commit and push changes to main branch
      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git checkout main

          git add downloads/script1/*  # Files from script1.py
          git add downloads/script2/*  # Files from script2.py
          git add downloads/script3/*  # Files from script3.py

          git commit -m "Daily database update"

          git push -u https://$PAT_TOKEN@github.com/your-username/your-repo.git main