name: Update Database

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: 

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.13.0
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.0

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run HSR database update
        run: python hsr.py
      
      - name: Create download directories
        run: |
          mkdir - output/hsr

      - name: Add files to Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/hsr/*

      - name: Commit changes
        run: |
          git commit -m "Daily database update" || echo "No changes to commit"

      - name: Push changes
        run: git push