name: Run Downloader Script

on:
  schedule:
    - cron: "0 3 * * *"    # Runs daily at 03:00 Jakarta time
    - cron: "0 3 * * 1"    # Runs weekly on Monday at 03:00 Jakarta time
    - cron: "*/2 * * * *"   # Debug

jobs:
  download_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13.0"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run downloader script for daily task
        if: github.event_name == 'schedule' && github.event.schedule == '0 3 * * *'  # Check for the daily schedule
        run: python app.py daily.txt

      - name: Run downloader script for weekly task
        if: github.event_name == 'schedule' && github.event.schedule == '0 3 * * 1'  # Check for the weekly schedule
        run: python app.py weekly.txt

      - name: Run downloader script for debug
        if: github.event_name == 'schedule' && github.event.schedule == '*/2 * * * *'  # Check for the debug schedule
        run: python app.py debug.txt
